@import com.jsoniter.any.Any
@args (Any config, String expose)
FROM openjdk:8-jre-alpine
#EXPOSE @expose
@with (name = config.get("artifactId") + ".jar") {ADD /build/libs/@name server.jar}
CMD ["/bin/sh","-c","java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dlight-4j-config-dir=/config -Dlogback.configurationFile=/config/logback.xml -jar /server.jar"]