@import java.util.Map
@args (Map<String, Object> config)
FROM openjdk:8-jre-alpine
EXPOSE 8080
@with (name = config.get("artifactId") + "-" + config.get("version") + ".jar") {ADD /target/@name server.jar}
CMD ["/bin/sh","-c","java -Dlight-java-config-dir=/config -cp /server.jar:/service com.networknt.server.Server"]
